- name: Install php5-fpm and php5-cli
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-fpm
    - php5-cli

- name: Copy fpm specific configuration
  copy: src=etc/php5/fpm/conf.d/global_fpm.ini dest=/etc/php5/fpm/conf.d/global_fpm.ini
  notify:
    - restart nginx
    - restart php5-fpm