---
# database configuration

- name: install MySQL
  apt: pkg={{ item }} state=latest update-cache=yes
  with_items:
    - mysql-server
    - python-mysqldb

- name: start the MySQL service
  action: service name=mysql state=started

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql.password }} priv=*.*:ALL,GRANT
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=etc/mysql/my.cnf dest=~/.my.cnf owner=root mode=0600
  notify: restart mysql

- name: delete anonymous MySQL server user
  mysql_user: name="" host={{ item }} state="absent"
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost

- name: configure MySQL database
  mysql_db: name={{ mysql.database }} state=present

- name: configure MySQL user
  mysql_user: name={{ mysql.user }} password={{ mysql.password }} host={{ item }} priv=*.*:ALL
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost
