---
- hosts: all
  sudo: true
  vars:
    doc_root: /var/www/web
    sys_packages: ["vim", "git"]
    php_packages: ["php5-cli","php5-common","php5-imap","php5-sqlite", "php5-intl", "php5-curl", "php5-mysql"]
    php_ppa: php5
    mysql:
      user: ibsciss
      password: ibsciss
      database: ibsciss
  roles:
    - init
    - nginx
    - php5-fpm
    - mysql
    - composer
    - phpcommon