---
- hosts: all
  sudo: true
  vars:
    doc_root: /vagrant
    sys_packages: ["vim"]
    php_packages: ["php5-cli","php5-common","php5-imap","php5-sqlite"]
    php_ppa: php5
  roles:
    - init
    - nginx
    - php5-fpm
    - composer
    - phpcommon
