---
- hosts: all
  sudo: true
  vars:
<<<<<<< HEAD
    doc_root: /var/www/web
    sys_packages: ["vim"]
    php_packages: ["php5-cli","php5-common","php5-imap","php5-sqlite", "php5-intl", "php5-curl", "php5-mysql"]
    php_ppa: php5
    mysql:
      user: ibsciss
      password: ibsciss
      database: ibsciss
=======
    doc_root: /vagrant
    sys_packages: ["vim"]
    php_packages: ["php5-cli","php5-common","php5-imap","php5-sqlite"]
    php_ppa: php5
>>>>>>> ef2c217e5732c2ef4edb265136acca37f13bef62
  roles:
    - init
    - nginx
    - php5-fpm
<<<<<<< HEAD
    - mysql
    - composer
    - phpcommon
=======
    - composer
    - phpcommon
>>>>>>> ef2c217e5732c2ef4edb265136acca37f13bef62
